version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
#- ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./esdata:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
    env_file:
      - env.env

networks:
  default:
    external:
      name: service