version: '2'
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
#    command: >
#      --requirepass "123456"
    volumes:
      - ./data:/data

networks:
  default:
    external:
      name: service